Algoritmo "Ex1"

Var
n1:inteiro

Inicio
escreval ("Digite um número inteiro : ")
leia (n1)

se (n1 mod 2)=1 e (n1>0) entao

   escreval ("Seu número é impar positivo")
   
fimse

se (n1 mod 2)=1 e (n1<0) entao

   escreval ("Seu número é impar negativo")
   
fimse

se (n1 mod 2)=0 e (n1>0) entao

   escreval ("Seu número é par positivo")
   
fimse

se (n1 mod 2)=0 e (n1<0) entao

   escreval ("Seu número é par negativo")
   
fimse

Fimalgoritmo